name: PHP CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '7.4'
            env:
              ANALYSIS: true
          - php-version: '7.4'
            env:
              COMPOSER_ARGS: '--prefer-lowest'
          - php-version: '8.1'
          - php-version: '8.2'
          - php-version: '8.3'
          - php-version: '8.4'
          - php-version: 'nightly'
            env:
              COMPOSER_ARGS: '--ignore-platform-reqs'
      allow-failure:
        - php-version: 'nightly'

    name: PHP ${{ matrix.php-version }} tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2
          extensions: mbstring, intl

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer update ${{ matrix.env.COMPOSER_ARGS || '' }}

      - name: Run PHPUnit
        run: |
          mkdir -p build/logs
          php vendor/bin/phpunit -c phpunit.xml.dist

      - name: Run PHPCS (if ANALYSIS=true)
        if: ${{ matrix.env.ANALYSIS == 'true' }}
        run: php vendor/bin/phpcs

      - name: Upload coverage to Coveralls (if ANALYSIS=true)
        if: ${{ matrix.env.ANALYSIS == 'true' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: php vendor/bin/coveralls -v -r $GITHUB_WORKSPACE
